# Toms obvious markup lang
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Curriculum Vitae'
theme = 'hulga'

[params]
name = "JSON Alexander"

# Pages, page links
[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Application Development"
  pageRef = "/appdev"
  weight = 2

[[menu.main]]
  name = "Cloud Infrastructure & DevOps"
  pageRef = "/cloud"
  weight = 3

[[menu.main]]
  name = "Web Development"
  pageRef = "/webdev"
  weight = 4

[[menu.main]]
  name = "CLI & Other Tooling"
  pageRef = "/cli"
  weight = 5
