# Toms obvious markup lang
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Curriculum Vitae'
theme = 'hulga'

[params]
name = "JSON Alexander"

# Pages, page links
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
  name = "Application Development"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Cloud Infrastructure & DevOps"
  url = "/posts/"
  weight = 3

[[menu.main]]
  name = "Web Development"
  url = "/posts/"
  weight = 4

[[menu.main]]
  name = "CLI & Other Tooling"
  url = "/posts/"
  weight = 5
