# Toms obvious markup lang
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Curriculum Vitae'
theme = 'hulga'

[params]
name = "JSON Alexander"
keywords = "HTML, hugo, CSS"
description = "Matthew McCabe's CV"
copyright = "Copyright Â© 2026 Matthew McCabe. All rights reserved."

# change bulma's primary color
# primaryColor = "#3e50b4"
primaryColor = "#1d9bf0"

# change bulma's link color (secondary color in this theme)
linkColor = "#0f172b"

# subtitle on homepage
subtitle = "Matthew McCabe"

# Pages, page links
[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Application Development"
  pageRef = "/appdev"
  weight = 2

[[menu.main]]
  name = "Cloud Infrastructure & DevOps"
  pageRef = "/cloud"
  weight = 3

[[menu.main]]
  name = "Web Development"
  pageRef = "/webdev"
  weight = 4

[[menu.main]]
  name = "CLI & Other Tooling"
  pageRef = "/cli"
  weight = 5
