# Toms obvious markup lang
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Curriculum Vitae'
theme = 'hulga'

[params]
name = "JSON Alexander"

  copyright = "Copyright Â© 2026 Matthew McCabe. All rights reserved."

  # enable prefers-color-scheme:dark, default false
  darkMedia = true

  # enable user to toggle dark mode with a menu, default false
  darkToggle = true


# Pages, page links
[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Application Development"
  pageRef = "/appdev"
  weight = 2

[[menu.main]]
  name = "Cloud Infrastructure & DevOps"
  pageRef = "/cloud"
  weight = 3

[[menu.main]]
  name = "Web Development"
  pageRef = "/webdev"
  weight = 4

[[menu.main]]
  name = "CLI & Other Tooling"
  pageRef = "/cli"
  weight = 5
